# dabs_cicd_demo_dev.yaml
name: Deploy to dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4  

      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy
        working-directory: ./dabs_cicd_demo
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  workflow_run:
    name: "Job run for the workflow"
    runs-on: ubuntu-latest
    environment: dev

    needs:
      - deploy

    steps:
      - uses: actions/checkout@v4

      - uses: databricks/setup-cli@main

      - shell: bash
        name: Run pipeline update
        run: |
          databricks bundle run demo_dabs_project_job --refresh-all 2>&1 | tee output.log
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  workflow_run:
    name: "DBT Job run for the workflow"
    runs-on: ubuntu-latest
    environment: dev

    needs:
      - deploy

    steps:
      - uses: actions/checkout@v4

      - uses: databricks/setup-cli@main

      - shell: bash
        name: Run pipeline update
        run: |
          databricks bundle run demo_dabs_project_dbt_job --refresh-all 2>&1 | tee output.log
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev