# dabs_cicd_demo_dev.yaml
name: Deploy to dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v5

      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy
        working-directory: ./dabs_cicd_demo
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev
